cours/urls.py
"""victorhugo URL Configuration
"""
from django.contrib import admin
from django.conf.urls import include,url
from django.conf.urls.static import static
from django.urls import path
from . import views

app_name = 'cours'

urlpatterns = [
    #path(r'', views.home, name='home'),
    url(r'^matieres_list$', views.matieres_list, name='matieres_list'),
    url(r'^classes_list$', views.classes_list, name='classes_list'),
    url(r'^eleves_list$', views.eleves_list, name='eleves_list'),
    url(r'^presence_list$', views.presence_list, name='presence_list'),
    url(r'^eleve_update/(?P<pk>\d+)$', views.eleve_update, name='eleve_update'),	
    url(r'^eleve_file/(?P<pk>\d+)$', views.eleve_file, name='eleve_file'),	
    url(r'^eleve_add$', views.eleve_add, name='eleve_add'),
    url(r'^enseignants_list$', views.enseignants_list, name='enseignants_list'),
    url(r'^enseignant_update/(?P<pk>\d+)$', views.enseignant_update, name='enseignant_update'),
    url(r'^enseignant_file/(?P<pk>\d+)$', views.enseignant_file, name='enseignant_file'),	
    url(r'^enseignant_add$', views.enseignant_add, name='enseignant_add'),

]

templates/about.html
{% extends "base.html" %}
{% load version %}

{%  block content %}
<div class="row">
	<div class='col-sm-6 col-sm-offset-3'>
		<h1>A propos de nous </h1>
		<p>Lycée Victor Hugo </p>
		<p>version 0.01 </p>
			<span class='version'>Dernière mise à jour: {% version_date %}</span>
		<hr />
		<p></p>
		<p> <i class="fa fa-copyright" aria-hidden="true"></i> Copyright Lycée Victor Hugo 2019 </p>
	</div>
</div>

{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'img/lvh.jpg' %}">
    <meta name="keywords" content="lycée victor hugo">
    <meta name="HandheldFriendly" content="True">
    <meta name="MobileOptimized" content="320">
    <title>{% block head_title %}LYCEE VICTOR HUGO {% endblock %}</title>
    {% include 'javascript.html' %}
    {% include 'head_css.html' %}
    
    <style>
    {% block style%}
 
    {% endblock %}
    </style>
    </head>

  <body>
{% include 'navbar.html' %}

<br />
 {% block jumbotron %}
      {% endblock %}
    <div class="container">
      
      {% block content %}      
      
      {% endblock %}
     </div>
  </body>
</html>

templates/forms.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}


<div class='row'>
<div class='col-sm-6 col-sm-offset-3'>	
{% if title %}
	<h1 class='text-align-center'>{{ title }} <i class="fa fa-pencil-square-o" aria-hidden="true"></i></h1>
{% endif %}
<form method='POST'  action=''>
	{% csrf_token %}
	{{form | crispy}}

<input class='btn btn-default' type='submit' value='Send' />

</form>
</div>
</div>

{% endblock %}

templates/head_css.html
{% load staticfiles %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">


<!-- <link href="{% static 'css/navbar-static-top.css' %}" rel="stylesheet">
<link href="{% static 'css/custom.css' %}" rel="stylesheet"> 
<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'css/style.min.css' %}" rel="stylesheet"> -->

<style type="text/css">
    body {
        padding-top: 60px;
    }
</style>

templates/home.html
{% extends "base.html" %}

{% load static %} 
{% block head_title %} Lycée Victor Hugo  | {{ block.super }} {% endblock %}

<style>
{% block style %}
.navbar-static-top {
	margin-bottom: 0px !important;
	background-color:#93b3ee;
}
.jumbotron {
	background-color:#93b3ee;
	color:#fff;
}
{% endblock %}
</style>

{% block content %}
<body>

  <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-60 h-20" src="{% static 'img/ecole.jpg' %}" alt="First slide">
      <div class="carousel-caption d-none d-md-block"> 
  </div>
    </div>
    <div class="carousel-item">
      <img class="d-block w-60 h-20" src="{% static 'img/etudiants.jpg' %}" alt="Second slide">
      <div class="carousel-caption d-none d-md-block">  
  </div>
    </div>
    <div class="carousel-item">
      <img class="d-block w-60 h-20" src="{% static 'img/work.jpg' %}" alt="Third slide">
      <div class="carousel-caption d-none d-md-block">
  </div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<hr class="featurette-divider">
    <div class="featurette">
        <img class="featurette-image pull-center" src="{{STATIC_URL}}img/nature.jpg">
        <h2 class="featurette-heading">Enseignement international</h2>
        <p class="lead">Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur.</p>
      </div>
      <hr class="featurette-divider">
      <div class="featurette">
        <img class="featurette-image pull-center" src="{{STATIC_URL}}img/activities.jpg">
        <h2 class="featurette-heading">Plus de 2000 élèves chaque année</h2>
        <p class="lead">Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt</p>
      </div>
      <hr class="featurette-divider">
      <div class="featurette">
        <img class="featurette-image pull-center" src="{{STATIC_URL}}img/globe.jpg">
        <h2 class="featurette-heading">La nature à proximité</h2>
        <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      </div>
      
	{% endblock %}
</body> 

templates/javascript.html
{% load staticfiles %}

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

templates/navbar.html
{% load static %}
<nav class="navbar navbar-default fixed-top navbar-expand-lg navbar-light bg-light">
  <div class="container">
 <!--  <nav class="navbar navbar-expand-lg navbar-dark indigo"> -->
   <img src="{% static 'img/lvh.jpg' %}" width="60px" class="d-inline-block align-left" alt="Lycee">
    <a class="navbar-brand" href="#">Lycée Victor Hugo</a>

<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  
 <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

          <li class="nav-item active"> <a class="nav-link" href="{% url 'home' %}">Accueil<span class="sr-only">(current)</span></a>
          </li>

            {% if request.user.is_staff %}

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Administration</a>
               <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'cours:matieres_list' %}">Matières disponibles</a>
                <a class="dropdown-item" href="{% url 'cours:classes_list' %}">Les classes</a>
                
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'cours:enseignants_list' %}">Les enseignants</a>
                <a class="dropdown-item" href="">Le planning</a>
                
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'cours:eleves_list' %}">Nos élèves</a>
                <a class="dropdown-item" href="{% url 'cours:presence_list' %}">L'état de présence</a>
                
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="">Toutes les évaluations</a>
                <a class="dropdown-item" href="">Les notes</a>
                </div>
              </li>
              
         {% endif %}
    
              <li class="nav-item">
                  <a class="nav-link" href="">Vie de l'école</a>
              </li>
             

          {% if request.user.is_authenticated and not request.user.is_staff %}
                    
                    <li class="nav-item dropdown">
                       <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">MySpace</a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                       <a class="dropdown-item" href="">My profile</a>
                       <a class="dropdown-item" href="">Update my profile</a>
                   </div></li>
         
           {% endif %}
              <li class="nav-item">
                  <a class="nav-link" href="">A propos de </a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="">Contact</a>
              </li>
              
          {% if request.user.is_authenticated %}
              <li class="nav-item">
              <a  class="nav-link" href="{% url 'logout' %}">Déconnecter</a>
              </li>
          {% endif %}

          {% if not request.user.is_authenticated and not "/accounts/login" in request.get_full_path %}
              <li class="nav-item">
              <a  class="nav-link" href="{% url 'login' %}">Se connecter</a>
              </li>
          {% endif %}
        </ul> 
      </div>
   </nav>