cours/urls.py
"""victorhugo URL Configuration
"""
from django.contrib import admin
from django.conf.urls import include,url
from django.conf.urls.static import static
from django.urls import path
from . import views

app_name = 'cours'

urlpatterns = [
    #path(r'', views.home, name='home'),
    url(r'^matieres_list$', views.matieres_list, name='matieres_list'),
    url(r'^classes_list$', views.classes_list, name='classes_list'),
    url(r'^eleves_list$', views.eleves_list, name='eleves_list'),
    url(r'^presence_list$', views.presence_list, name='presence_list'),
    url(r'^eleve_update/(?P<pk>\d+)$', views.eleve_update, name='eleve_update'),	
    url(r'^eleve_file/(?P<pk>\d+)$', views.eleve_file, name='eleve_file'),	
    url(r'^eleve_add$', views.eleve_add, name='eleve_add'),
    url(r'^enseignants_list$', views.enseignants_list, name='enseignants_list'),
    url(r'^enseignant_update/(?P<pk>\d+)$', views.enseignant_update, name='enseignant_update'),
    url(r'^enseignant_file/(?P<pk>\d+)$', views.enseignant_file, name='enseignant_file'),	
    url(r'^enseignant_add$', views.enseignant_add, name='enseignant_add'),

]

cours/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.urls import reverse
import datetime

# Create your models here.


class sexe(models.Model):
    libelle_sexe = models.CharField(max_length=1, blank=True)
    class Meta:
    	verbose_name = 'sexe'
    	verbose_name_plural = 'sexe'
    def __str__(self):
        return self.libelle_sexe

class matiere(models.Model):
    libelle_matiere = models.CharField(max_length=30, blank=True)
    class Meta:
    	verbose_name = 'matière'
    	verbose_name_plural = 'matières'
    def __str__(self):
        return self.libelle_matiere
    def get_absolute_url(self):
        return reverse('matières_detail', args=[str(self.id)])

class classe(models.Model):
    libelle_classe = models.CharField(max_length=10, blank=True)
    class Meta:
    	verbose_name = 'classe'
    	verbose_name_plural = 'classes'
    def __str__(self):
        return self.libelle_classe
    def get_absolute_url(self):
        return reverse('classe_detail', args=[str(self.id)])
 

class salle(models.Model):
    libelle_salle = models.CharField(max_length=10, blank=True)
    capacite = models.IntegerField(blank=True, default=0)
    localisation = models.CharField(max_length=30, blank=True)
    class Meta:
    	verbose_name = 'salle'
    	verbose_name_plural = 'salles'
    def __str__(self):
        return self.libelle_salle
    def get_absolute_url(self):
        return reverse('salle_detail', args=[str(self.id)])

class type_evaluation(models.Model):
    libelle_type_evaluation = models.CharField(max_length=30, blank=True)
    class Meta:
    	verbose_name = "type d'évaluation"
    	verbose_name_plural = "types d'évaluation"
    def __str__(self):
        return self.libelle_type_evaluation

class eleve(models.Model):
	nom = models.CharField(max_length=30, blank=True)
	prenom = models.CharField(max_length=30, blank=True)
	date_naissance = models.DateField(blank=True, null=True)
	sexe = models.ForeignKey('sexe', on_delete=models.CASCADE, null=True )
	classe = models.ForeignKey('classe', on_delete=models.CASCADE, blank=True, null=True)
	class Meta:
		verbose_name = 'élève'
		verbose_name_plural = 'élèves'
		ordering = ['-nom']
	def __str__(self):
		return '%s %s' % (self.nom, self.prenom)
	def get_absolute_url(self):
		return reverse('élève_detail', args=[str(self.id)])

class evaluation(models.Model):
	libelle_evaluation = models.CharField(max_length=10, blank=True)
	date_evaluation = models.DateTimeField()
	coefficient = models.PositiveSmallIntegerField()
	type_evaluation = models.ForeignKey('type_evaluation', on_delete=models.CASCADE )
	matiere = models.ForeignKey('matiere', on_delete=models.CASCADE)
	class Meta:
		verbose_name = 'évaluation'
		verbose_name_plural = 'évaluations'
	def __str__(self):
		return self.libelle_evaluation

class enseignant(models.Model):
	nom = models.CharField(max_length=30, blank=True,)
	prenom = models.CharField(max_length=30, blank=True)
	sexe = models.ForeignKey('sexe', on_delete=models.CASCADE, null=True)
	telephone = models.CharField(max_length=25, blank=True)
	class Meta:
		verbose_name ='enseignant'
		verbose_name_plural = 'enseignants'
		ordering = ['nom']
	def __str__(self):
		return '%s %s' % (self.nom, self.prenom)
	def get_absolute_url(self):
		return reverse('enseignant_detail', args=[str(self.id)])

class cours(models.Model):
	code_court = models.CharField(max_length=5)
	description = models.CharField(max_length=30)
	date = models.DateField()
	heure_debut = models.TimeField()
	heure_fin = models.TimeField()
	salle = models.ForeignKey('salle', on_delete=models.CASCADE, null=True)
	classe = models.ForeignKey('classe', on_delete=models.CASCADE, null=True)
	enseignant = models.ForeignKey('enseignant', on_delete=models.CASCADE, null=True)
	class Meta:
		indexes = [models.Index(fields=['code_court'])]
		verbose_name = 'cours'
		verbose_name_plural = 'cours'
	def __str__(self):
		return '%s %s %s %s %s' % (self.date, self.salle, self.enseignant, self.classe, self.description)
	def get_absolute_url(self):
		return reverse('cours_detail', args=[str(self.id)])

class passer_evaluation(models.Model):
	note = models.FloatField()
	present = models.BooleanField(default=False)
	evaluation = models.ForeignKey('evaluation', on_delete=models.CASCADE)
	eleve = models.ForeignKey('eleve', on_delete=models.CASCADE)
	class Meta:
		verbose_name = 'passer évaluation'
		verbose_name_plural = 'passe évaluation'
	def __str__(self):
		return '%s %s' % (self.eleve, self.note)

class enseigner(models.Model):
	matiere = models.ForeignKey('matiere', on_delete=models.CASCADE)
	enseignant = models.ForeignKey('enseignant', on_delete=models.CASCADE)
	class Meta:
		verbose_name = 'enseigner'
		verbose_name_plural = 'enseigner'
	def __str__(self):
		return '%s %s' % (self.enseignant, self.matiere)

class presence(models.Model):
	date = models.DateField('Date de présence')
	eleve = models.ForeignKey('eleve', on_delete=models.CASCADE)
	present = models.BooleanField('présent', default=True)
	class Meta:
		verbose_name = 'présence'
		verbose_name_plural = 'présence'
	def __str__(self):
		return '%s %s' % (self.eleve, self.present)

cours/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.forms import ModelForm, Form, modelformset_factory
from crispy_forms.layout import Submit, Layout, Field, Button, ButtonHolder
from crispy_forms.bootstrap import TabHolder, Tab, FormActions, StrictButton
from crispy_forms.helper import FormHelper
from django.forms import Form, ModelForm
from cours.models import *
from django.conf import settings

# next version

class EleveForm(forms.ModelForm):
    class Meta:
        model = eleve
        fields = ('__all__')

    def __init__(self, *args, **kwargs):
        super(EleveForm, self).__init__(*args, **kwargs)    
        self.fields['prenom'].required=False
        self.fields['prenom'].label = "Prénom"
        self.fields['nom'].required=False
        self.fields['nom'].label = "Nom"
        self.fields['date_naissance'].required=False
        self.fields['date_naissance'].label = "Date de naissance"
        self.fields['sexe'].label = "Sexe"
        self.fields['sexe']=forms.ModelChoiceField(queryset=sexe.objects.all())
        self.fields['sexe'].required=False
        self.fields['classe'].label = "Classe"
        self.fields['classe']=forms.ModelChoiceField(queryset=classe.objects.all())
        self.fields['classe'].required=False
    helper = FormHelper()
    helper.form_method = 'POST'
    helper.form_class = 'form-horizontal'
    helper.form_id = 'user_form'
    helper.label_class = 'col-md-4'
    helper.field_class = 'col-md-6' 
    helper.layout = Layout(
        TabHolder(
            Tab(
                'Contact',
                'prenom',
                'nom',
                'date_naissance',
                'sexe',
                'classe',
            ),
        ),  
        FormActions(
            Submit('save','Enregistrer', css_class="btn-success"),
            Submit('cancel','Annuler', css_class="btn-cancel"),
        ), 
    )


class EnseignantsForm(forms.ModelForm):
    class Meta:
        model = enseignant
        fields = ('__all__')

    def __init__(self, *args, **kwargs):
        super(EnseignantsForm, self).__init__(*args, **kwargs)    
        self.fields['prenom'].required=False
        self.fields['prenom'].label = "Prénom"
        self.fields['nom'].required=False
        self.fields['nom'].label = "Nom"
       
        self.fields['sexe'].label = "Sexe"
        self.fields['sexe']=forms.ModelChoiceField(queryset=sexe.objects.all())
        self.fields['sexe'].required=False
        self.fields['telephone'].label = "Téléphone"
        self.fields['telephone'].required=False
    helper = FormHelper()
    helper.form_method = 'POST'
    helper.form_class = 'form-horizontal'
    helper.form_id = 'user_form'
    helper.label_class = 'col-md-4'
    helper.field_class = 'col-md-6' 
    helper.layout = Layout(
        TabHolder(
            Tab(
                'Contact',
                'prenom',
                'nom',
                'sexe',
                'telephone',
            ),
        ),  
        FormActions(
            Submit('save','Enregistrer', css_class="btn-success"),
            Submit('cancel','Annuler', css_class="btn-cancel"),
        ), 
    )

cours/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, render_to_response,redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import sexe, matiere, classe, salle, type_evaluation, eleve, evaluation, enseignant, cours, passer_evaluation, enseigner, presence
from .forms import EleveForm, EnseignantsForm

@login_required
def matieres_list(request, template_name='cours/matieres_list.html'):
    current_user = request.user
    lists= matiere.objects.all()
    results_lists=lists.count()
    paginator = Paginator(lists, 20)
    page = request.GET.get('page')
    try:
        docus = paginator.page(page)
    except PageNotAnInteger:
        docus = paginator.page(1)
    except EmptyPage:
        docus = paginator.page(paginator.num_pages)
    return render(request,template_name, {'docus': docus ,'page': page , 'results_lists':results_lists})

@login_required
def classes_list(request, template_name='cours/classes_list.html'):
    current_user = request.user
    lists= classe.objects.all()
    results_lists=lists.count()
    paginator = Paginator(lists, 10)
    page = request.GET.get('page')
    try:
        docus = paginator.page(page)
    except PageNotAnInteger:
        docus = paginator.page(1)
    except EmptyPage:
        docus = paginator.page(paginator.num_pages)
    return render(request,template_name, {'docus': docus ,'page': page , 'results_lists':results_lists})

@login_required
def presence_list(request, template_name='cours/presences.html'):
    current_user = request.user
    lists= presence.objects.all()
    paginator = Paginator(lists, 10)
    page = request.GET.get('page')
    try:
        docus = paginator.page(page)
    except PageNotAnInteger:
        docus = paginator.page(1)
    except EmptyPage:
        docus = paginator.page(paginator.num_pages)
    return render(request,template_name, {'docus': docus ,'page': page })


@login_required
def eleves_list(request, template_name='cours/eleves_list.html'):
    current_user = request.user
    lists= eleve.objects.order_by('nom')
    results_lists=lists.count()
    paginator = Paginator(lists, 20)
    page = request.GET.get('page')
    try:
        docus = paginator.page(page)
    except PageNotAnInteger:
        docus = paginator.page(1)
    except EmptyPage:
        docus = paginator.page(paginator.num_pages)
    return render(request,template_name, {'docus': docus ,'page': page , 'results_lists':results_lists})


@login_required
def eleve_file(request, pk, template_name='cours/eleve_fiche.html'):
	data = eleve.objects.filter(id__exact=pk)
	return render(request, template_name, {'data': data})

@login_required
def eleve_add(request, template_name='cours/eleve_form.html'):
    form = EleveForm(request.POST or None,request.FILES or None)
    if form.is_valid():
        docus = form.save(commit=False)
        docus.user = request.user
        docus.save()
        return redirect('/cours/eleves_list', permanent=True)
    return render(request, template_name, {'form':form})

@login_required
def eleve_update(request, pk, template_name='cours/eleve_form.html'):
    if request.user.is_staff:
        docus= get_object_or_404(eleve, pk=pk)
    else:
        docus= get_object_or_404(eleve, pk=pk, user=request.user)
    form = EleveForm(request.POST or None,request.FILES or None, instance=docus)
    if form.is_valid():
        form.save()
        return redirect('/cours/eleves_list', permanent=True)
    return render(request, template_name, {'form':form})

@login_required
def enseignants_list(request, template_name='cours/enseignants_list.html'):
    current_user = request.user
    lists= enseignant.objects.order_by('nom')
    results_lists=lists.count()
    paginator = Paginator(lists, 20)
    page = request.GET.get('page')
    try:
        docus = paginator.page(page)
    except PageNotAnInteger:
        docus = paginator.page(1)
    except EmptyPage:
        docus = paginator.page(paginator.num_pages)
    return render(request,template_name, {'docus': docus,'page': page , 'results_lists':results_lists})

@login_required
def enseignant_update(request, pk, template_name='cours/enseignant_form.html'):
    if request.user.is_staff:
        docus= get_object_or_404(enseignant, pk=pk)
    else:
        docus= get_object_or_404(enseignant, pk=pk, user=request.user)
    form = EnseignantsForm(request.POST or None,request.FILES or None, instance=docus)
    if form.is_valid():
        form.save()
        return redirect('/cours/enseignants_list', permanent=True)
    return render(request, template_name, {'form':form})

@login_required
def enseignant_file(request, pk, template_name='cours/enseignant_fiche.html'):
	data = enseignant.objects.filter(id__exact=pk)
	return render(request, template_name, {'data': data})

@login_required
def enseignant_add(request, template_name='cours/enseignant_form.html'):
    form = EnseignantsForm(request.POST or None,request.FILES or None)
    if form.is_valid():
        docus = form.save(commit=False)
        docus.user = request.user
        docus.save()
        return redirect('/cours/enseignants_list', permanent=True)
    return render(request, template_name, {'form':form})

templates/cours/eleve_fiche.html
{% extends "base.html" %}

{% load static %}
{% block head_title %} ELEVES | {{ block.super }} {% endblock %}

<style>
{% block style %}
.navbar-static-top {
        margin-bottom: 0px !important;
        background-color:#93b3ee;
}
.jumbotron {
        background-color:#93b3ee;
        color:#fff;
}
{% endblock %}
</style>

        {% block content %}
        {% if request.user.is_authenticated %}
            <div class="row">
                <div class="col-md-12">
                                   
                    <h2>Fiche élève</h2>
                </div>
            </div>
            
                {% for eleve in data %}
                    <div class="row">
                        <label class="col-6 col-md-4 col-form-label">Nom</label>
                        <div class="col-6 col-md-4">{{ eleve.nom }}</div>
                    </div>
                    <div class="row">
                        <label class="col-6 col-md-4 col-form-label">Prénom</label>
                        <div class="col-6 col-md-4">{{ eleve.prenom }}</div>
                    </div>
                    <div class="row">
                        <label class="col-6 col-sm-4 col-form-label">Date de naissance</label>
                        <div class="col-6 col-md-4">{{ eleve.date_naissance }}</div>
                    </div>
                    <div class="row">
                        <label class="col-6 col-md-4 col-form-label">Age</label>
                        <div class="col-6 col-md-4">{{ eleve.age }}</div>
                    </div>
                    <div class="row">
                        <label class="col-6 col-md-4 col-form-label">Sexe</label>
                        {% if eleve.sexe  == H %}

                        <div class="col-6 col-md-4">Homme</div> 
                        {% elif eleve.sexe == F %}
                        <div class="col-6 col-md-4">Femme</div> 
                        {% else %}
                        <div class="col-6 col-md-4">Inconnu</div> 
                        {% endif %}
                    </div>
                    <div class="row">
                        <label class="col-6 col-md-4 col-form-label">Classe</label>
                        <div class="col-6 col-md-4">{{ eleve.classe }}</div>
                    </div>

                     
<br />
<br />
    
        <div class="row">
                <div class='col-sm-2'>
                    <p><a class="btn btn-md btn-primary" href="{% url 'cours:eleve_update' eleve.id %}" role="button">Modifier</a></td>
                </div>
                <div class='col-sm-2'>
                    <p><a class="btn btn-md btn-primary" href="/cours/eleve_add" role="button">Nouvelle Inscription</a></p> 
                </div>
                <div class='col-sm-2'>   
                    <p><a class="btn btn-md btn-primary" href="{% url 'cours:eleves_list' %}" role="button">Retour liste élèves</a></p>
                </div>
                <div class='col-sm-2'>   
                    <p><a class="btn btn-md btn-primary" href="{% url 'home' %}" role="button">Retour Menu</a></p>
                </div>
                <div class='col-sm-2'>
                </div>
                <div class='col-sm-2'>
                </div>
        </div> <!-- end row -->
        <!-- </div> -->

 {% endfor %}

        {% else %}
    <h1>Need to log in </h1>
    {% endif %}
        {% endblock %}

templates/cours/eleves_list.html
{% extends "base.html" %}

{% load static %}
{% block head_title %} ELEVES | {{ block.super }} {% endblock %}

<style>
{% block style %}
.navbar-static-top {
        margin-bottom: 0px !important;
        background-color:#93b3ee;
}
.jumbotron {
        background-color:#93b3ee;
        color:#fff;
}
{% endblock %}
</style>

        {% block content %}
        {% if request.user.is_authenticated %}
            <br />
            <br />

            <div class="row">
                <div class="col-md-4">
                    <h2>Liste des élèves </h2>
                </div>
                <div class="col-md-2">   
                    <H5> {{results_lists}} élèves </H5>
                </div>
                <div class="col-md-6"> 
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
            <div class="table-responsive-md">

                <br />
            {% if docus.has_other_pages %}
                    <ul class="pagination pagination-sm">
                    {% if docus.has_previous %}
                        <li class="page-item"><a class="page-link" href="?page={{ docus.previous_page_number }}">Previous</a></li>
                    {% else %}
                      <li class="page-item disabled"><a class="page-link" href=""><span>Previous</span></a></li>
                    {% endif %}

                    {% for i in docus.paginator.page_range %}
                        {% if i <= docus.number|add:5 and i >= docus.number|add:-5 %}
                            {% if docus.number == i %}
                                <li class="page-item active"><a class="page-link" ><span>{{ i }} <span class="sr-only">(current)</span></span></a></li>
                                {% else %}
                                <li class="page-item"><a class="page-link" href="?page={{forloop.counter}}">{{forloop.counter}}</a></li>
                            {% endif %} 
                         {% endif %} 
                    {% endfor %}
                    {% if docus.has_next %}
                      <li class="page-item"><a class="page-link" href="?page={{ docus.next_page_number }}">Next</a></li>
                    {% else %}
                      <li class="page-item disabled"><a class="page-link" href=""><span>Next</span></a></li>
                    {% endif %}
                  </ul>
                {% endif %}

            <table class="table table-borderd table-hover table-striped">   
                <thread>
                    <tr>
                        <th class="header">Nom</th>
                        <th class="header">Prenom</th>
                        <th class="header">Date de naissance</th>
                        <th class="header">Sexe</th>
                        <th class="header">Classe </th>
                    </tr>
                </tread>
                <tbody>
                    {% for eleve in docus %}
                    <tr>
                        <td>{{ eleve.nom }}</td>
                        <td>{{ eleve.prenom }}</td>
                        <td>{{ eleve.date_naissance|date:"d M Y"}}</td>
                        <td>{{ eleve.sexe }}</td>
                        <td>{{ eleve.classe }}</td>                     
                        <td align="center"> <a href="{% url 'cours:eleve_update' eleve.id %}"><button class="btn btn-primary btn-sm" data-title="Edit" data-toggle="modal" data-target="#edit" ><span class="glyphicon glyphicon-pencil">Modifier</span></button></a></td>
                        <td align="center"> <a href="{% url 'cours:eleve_file' eleve.id %}"><button class="btn btn-primary btn-sm" data-title="Fiche" data-toggle="modal" data-target="#edit" ><span class="glyphicon glyphicon-pencil">Fiche</span></button></a></td>                      
                        <td align="center"><a href=""><button class="btn btn-danger btn-sm" data-title="Delete" data-toggle="modal" data-target="#delete" ><span class="glyphicon glyphicon-trash">Archiver</span></button></p></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div> 
    </div> 
        </div> 
        <br />
        <div class="row">
                <div class='col-sm-3'>
                </div>          
                <div class='col-sm-2'>
                    <p><a class="btn btn-md btn-primary" href="/cours/eleve_add" role="button">Nouvelle Inscription</a></p> 
                </div>
                <div class='col-sm-2'>                
                <p><a class="btn btn-md btn-primary" href="{% url 'home' %}" role="button">Retour Menu</a></p>
                </div>
                <div class='col-sm-8'>
                </div>
        </div> 
        {% else %}
    <h1>Need to log in </h1>
    {% endif %}
        {% endblock %}

templates/cours/enseignant_fiche.html
{% extends "base.html" %}

{% load static %}
{% block head_title %} ELEVES | {{ block.super }} {% endblock %}

<style>
{% block style %}
.navbar-static-top {
        margin-bottom: 0px !important;
        background-color:#93b3ee;
}
.jumbotron {
        background-color:#93b3ee;
        color:#fff;
}
{% endblock %}
</style>

        {% block content %}
        {% if request.user.is_authenticated %}
            <div class="row">
                <div class="col-md-12">
                                   
                    <h2>Fiche enseignant</h2>
                </div>
            </div>
            
                {% for enseignant in data %}
                {{enseignant}}
                    <div class="row">
                        <label class="col-6 col-md-4 col-form-label">Nom</label>
                        <div class="col-6 col-md-4">{{ enseignant.nom }}</div>
                    </div>
                    <div class="row">
                        <label class="col-6 col-md-4 col-form-label">Prénom</label>
                        <div class="col-6 col-md-4">{{ enseignant.prenom }}</div>
                    </div>
                    
                    <div class="row">
                        <label class="col-6 col-md-4 col-form-label">Sexe</label>
                        <div class="col-6 col-md-4">{{ enseignant.sexe}}</div> 
                    </div>
                    <div class="row">
                        <label class="col-6 col-md-4 col-form-label">Téléphone</label>
                        <div class="col-6 col-md-4">{{ enseignant.telephone }}</div>
                    </div>

                     
<br />
<br />
    
        <div class="row">
                <div class='col-sm-2'>
                    <p><a class="btn btn-md btn-primary" href="{% url 'cours:enseignant_update' enseignant.id %}" role="button">Modifier</a></td>
                </div>
                <div class='col-sm-2'>
                    <p><a class="btn btn-md btn-primary" href="/cours/enseignant_add" role="button">Nouvel Enseignant</a></p> 
                </div>
                <div class='col-sm-2'>   
                    <p><a class="btn btn-md btn-primary" href="{% url 'cours:enseignants_list' %}" role="button">Retour enseignants</a></p>
                </div>
                <div class='col-sm-2'>   
                    <p><a class="btn btn-md btn-primary" href="{% url 'home' %}" role="button">Retour Menu</a></p>
                </div>
                <div class='col-sm-2'>
                </div>
                <div class='col-sm-2'>
                </div>
        </div> <!-- end row -->
        <!-- </div> -->

 {% endfor %}

        {% else %}
    <h1>Need to log in </h1>
    {% endif %}
        {% endblock %}

templates/cours/enseignants_list.html
{% extends "base.html" %}

{% load static %}
{% block head_title %} ENSEIGNANTS | {{ block.super }} {% endblock %}

<style>
{% block style %}
.navbar-static-top {
        margin-bottom: 0px !important;
        background-color:#93b3ee;
}
.jumbotron {
        background-color:#93b3ee;
        color:#fff;
}
{% endblock %}
</style>

        {% block content %}
        {% if request.user.is_authenticated %}
            <div class="row">
                <div class="col-md-4">
                    <h2>Liste des enseignants </h2>
                </div>
                <div class="col-md-2">   
                    <H5> {{results_lists}} enseignants </H5>
                </div>
                <div class="col-md-6"> 
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <br />
            {% if docus.has_other_pages %}
                    <ul class="pagination pagination-sm">
                    {% if docus.has_previous %}
                        <li class="page-item"><a class="page-link" href="?page={{ docus.previous_page_number }}">Previous</a></li>
                    {% else %}
                      <li class="page-item disabled"><a class="page-link" href=""><span>Previous</span></a></li>
                    {% endif %}

                    {% for i in docus.paginator.page_range %}
                        {% if i <= docus.number|add:5 and i >= docus.number|add:-5 %}
                            {% if docus.number == i %}
                                <li class="page-item active"><a class="page-link" ><span>{{ i }} <span class="sr-only">(current)</span></span></a></li>
                                {% else %}
                                <li class="page-item"><a class="page-link" href="?page={{forloop.counter}}">{{forloop.counter}}</a></li>
                            {% endif %} 
                         {% endif %} 
                    {% endfor %}

                    {% if docus.has_next %}
                      <li class="page-item"><a class="page-link" href="?page={{ docus.next_page_number }}">Next</a></li>
                    {% else %}
                      <li class="page-item disabled"><a class="page-link" href=""><span>Next</span></a></li>
                    {% endif %}
                  </ul>
                {% endif %}
            
            <div class="table-responsive-md">
            <table class="table table-borderd table-hover table-striped">   
                <thread>
                    <tr>
                        <th class="header">Nom</th>
                        <th class="header">Prenom</th>
                        <th class="header">Sexe</th>
                        <th class="header">Téléphone </th>
                        
                    </tr>
                </tread>
                <tbody>
                    {% for enseignant in docus %}
                    <tr>
                        <td>{{ enseignant.nom }}</td>
                        <td>{{ enseignant.prenom }}</td>
                        <td>{{ enseignant.sexe }}</td>
                        <td>{{ enseignant.telephone }}</td>
                        
                        <td align="center"> <a href="{% url 'cours:enseignant_update' enseignant.id %}"><button class="btn btn-primary btn-sm" data-title="Edit" data-toggle="modal" data-target="#edit" ><span class="glyphicon glyphicon-pencil">Modifier</span></button></a></td>

                        <td align="center"> <a href="{% url 'cours:enseignant_file' enseignant.id %}"><button class="btn btn-primary btn-sm" data-title="Fiche" data-toggle="modal" data-target="#edit" ><span class="glyphicon glyphicon-pencil">Fiche</span></button></a></td>
                        
                        <td align="center"><a href=""><button class="btn btn-danger btn-sm" data-title="Delete" data-toggle="modal" data-target="#delete" ><span class="glyphicon glyphicon-trash">Archiver</span></button></p></td>

                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div> 

                


    </div> 
        </div> 
    
        <div class="row">
                <div class='col-sm-3'>
                </div>
                
                <div class='col-sm-2'>
                    <p><a class="btn btn-md btn-primary" href="/cours/enseignement_add" role="button">Nouvelle Inscription</a></p> 
                </div>
                <div class='col-sm-2'>
                    
                <p><a class="btn btn-md btn-primary" href="{% url 'home' %}" role="button">Retour Menu</a></p>
                </div>
                <div class='col-sm-8'>
                </div>
        </div> <!-- end row -->
        <!-- </div> -->


        {% else %}
    <h1>Need to log in </h1>
    {% endif %}
        {% endblock %}